accounts/urls.py
'''
All the URL configs here are for the CMS redirects. These paths are only accessable for
authenticated users.
'''

from django.urls import path
from django.views.generic import TemplateView

from .views import AgentSubmitDocumentView, MyDocumentListView, verify_agent, confirm_verification
from blog.views import ArticleCreateView, ArticleDeleteView, ArticleUpdateView, MyArticleListView
from properties.views.house import (HouseCreateView, MyHouseListView, HouseUpdateView,
                                    HouseDeleteView)
from properties.views.apartment import (ApartmentCreateView, ApartmentUpdateView, ApartmentDeleteView, ApartmentUnitCreateView, ApartmentUnitDeleteView, 
                                        ApartmentUnitUpdateView, MyApartmentListView, MyApartmentUnitListView, ApartmentUnitDeleteView)

app_name = 'account'

urlpatterns = [
    path('', TemplateView.as_view(template_name='overview.html'), name='dashboard'),

    # apartments
    path('apartments/', MyApartmentListView.as_view(), name='apartment_list'),
    path('apartments/create/', ApartmentCreateView.as_view(), name='create_apartment'),
    path('apartments/<slug:slug>/update/', ApartmentUpdateView.as_view(), name='update_apartment'),
    path('apartments/<slug:slug>/delete/', ApartmentDeleteView.as_view(), name='delete_apartment'),
    # house 
    path('houses/', MyHouseListView.as_view(), name='house_list'),
    path('houses/add-house/', HouseCreateView.as_view(), name='create_house'),
    path('houses/<slug:slug>/update/', HouseUpdateView.as_view(), name='update_house'),
    path('houses/<slug:slug>/delete/', HouseDeleteView.as_view(), name='delete_house'),
    # apartment units
    path('units/', MyApartmentUnitListView.as_view(), name='apartmentunit_list'),
    path('units/add-unit/', ApartmentUnitCreateView.as_view(), name='create_unit'),
    path('units/<slug:slug>/update/', ApartmentUnitUpdateView.as_view(), name='update_unit'),
    path('units/<slug:slug>/delete/', ApartmentUnitDeleteView.as_view(), name='delete_unit'),
    # document
    path('documents/', MyDocumentListView.as_view(), name='document_list'),
    path('documents/<slug:slug>/verify/', verify_agent, name='verify_agent'),
    path('confirm-verification/<slug:slug>/', confirm_verification, name='confirm'),
    path('submit-document/', AgentSubmitDocumentView.as_view(), name='submit_document'),
    
    # blog articles
    
    path('articles/', MyArticleListView.as_view(), name='article_list'),
    path('articles/write-article/', ArticleCreateView.as_view(), name='write_article'),
    path('articles/<slug:slug>/update/', ArticleUpdateView.as_view(), name='update_article'),
    path('articles/<slug:slug>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

blog/urls.py
from django.urls import path

app_name = 'blog'

from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

real_estates/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from accounts.views import AgentRegistrationView, AgentProfileCreateView, AgentLisView
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('agents/', AgentLisView.as_view(), name='agent_list'),
    
    # AUTH urls
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', AgentRegistrationView.as_view(), name='register'),
    path('register/success/', AgentProfileCreateView.as_view(), name='registration_success'),
    
    #includes to other apps URLConfigs
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('properties/', include('properties.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models

from phonenumber_field.modelfields import PhoneNumberField

def user_directory_path(instance, file):
    # file will be saved to user seperated folders
    return 'logos/agent_{}/{}'.format(instance.user.id, file)


class Agent(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='agent', on_delete=models.CASCADE,
        primary_key=True)
    name = models.CharField(max_length=55)
    slug = models.SlugField(max_length=55)
    is_company = models.BooleanField(default=False)
    is_independent = models.BooleanField(default=False)
    about = models.TextField()
    phonenumber = PhoneNumberField(blank=True)
    line_id = models.CharField(max_length=25, unique=True, blank=True)
    logo = models.ImageField(upload_to=user_directory_path, default='logos/default.jpeg')
    verified = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class ContentManager(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
    primary_key=True)
    first_name = models.CharField(max_length=125)
    last_name = models.CharField(max_length=125)
    bio = models.TextField(max_length=255)

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class VerificicationDocument(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='document', on_delete=models.CASCADE)
    name = models.CharField(max_length=55)
    document = models.FileField(upload_to='documents')
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.utils.translation import ugettext_lazy as _

from core_app.models import CustomUser
from .models import Agent, ContentManager

class AgentRegistrationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ['email']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_agent = True
        user.save()
        return user

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from core_app.models import CustomUser
from .forms import AgentRegistrationForm
from .models import Agent, VerificicationDocument


class AgentRegistrationView(SuccessMessageMixin, CreateView):
    model = CustomUser
    form_class = AgentRegistrationForm
    success_message = '%(name)s with %(user.email)s has successfully been registered! Please fill in the profile form.'
    template_name = 'registration/register.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'agent'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        '''Authenticate the user after registering and redirect them
        to AgentProfileCreate'''
        user = form.save()
        login(self.request, user)
        return redirect('registration_success')


class AgentProfileCreateView(LoginRequiredMixin, CreateView):
    model = Agent
    fields = ['name', 'slug', 'is_company', 'is_independent',
            'about', 'phonenumber', 'line_id']
    template_name = 'registration/registration_success.html'
    success_url = reverse_lazy('account:house_list')

    def form_valid(self, form):
        # assign user to requested user
        form.instance.user = self.request.user
        return super().form_valid(form)


class AgentLisView(ListView):
    '''A view that returns all the agents'''
    model = Agent


class AgentSubmitDocumentView(LoginRequiredMixin, CreateView):
    model = VerificicationDocument
    fields = ['name', 'document']
    template_name = 'accounts/document_submit_form.html'
    success_url = reverse_lazy('account:house_list')

    def form_valid(self, form):
        # assign user to requested user
        form.instance.user = self.request.user
        return super().form_valid(form) 


class MyDocumentListView(LoginRequiredMixin, ListView):
    model = VerificicationDocument
    context_object_name = 'document_list'
    template_name = 'accounts/document_list.html'


'''Function views'''

def confirm_verification(request, slug):
    '''Confirm verification by change boolean value to True'''
    agent = Agent.objects.get(slug=slug)
    agent.verified = True
    agent.save()
    # redirect after confirmation
    return redirect('account:document_list')

def verify_agent(request, slug):
    '''View to be called on in uploaded document list to verify an agent''' 
    object = Agent.objects.get(slug=slug)
    context = {
        'object':object,
    }
    return render(request, 'accounts/verify_agent.html', context)
    

    



   

templates/accounts/agent_list.html
{% extends 'base.html' %}

{% block title %}Overview Agents{% endblock %}

{% block content %}
    <h1 class="title">Our agents</h1>
    <div class="columns is-multiline">
        {% for object in agent_list %}
            <div class="column is-2">
                <a href="">
                <div class="card">
                    <div class="card-header">
                        <div class="card-header-title">{{ object.name }}</div>
                    </div>
                    <div class="card-image">
                        <figure class="image is-5by3">
                            <img src="{{ object.logo.url }}" alt="{{ object.name }}">
                        </figure>
                    </div>
                    <div class="card-content">
                        <div class="content">
                            {{ object.apartmentunits.count }}
                        </div>
                    </div>
                </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/accounts/document_list.html
{% extends 'dashboard.html' %}

{% block title %} {% endblock title %}

{% block box %}

<div class="box">
    <h1 class="title">Documents & Verification</h1>
    
    {% if not document_list %}
    <p>Nothing</p>
    {% else %}
    <table class="table is-fullwidth is-hoverable">
        <thead>
            <tr>
                <th>Property Agent</th>
                <th>File</th>
                <th>Date</th>
                <th>Verified</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for object in document_list %}
            <tr>
                <td>{{ object.user.agent.name }}</td>
                <td><a href="{{ object.document.url }}">{{ object.name }}</a> </td>
                <td>{{ object.timestamp|date:'d M Y' }}</td>
                <td>
                    {% if object.user.agent.verified %}
                    <span class="icon"><i class="fas fa-check"></i></span>
                    {% else %}
                    <span class="icon"><i class="fas fa-times"></i></span>
                    {% endif %}
                </td>
                <td>
                    {% if object.user.agent.verified %}
                    No actions required
                    {% else %}
                    <a href="{% url 'account:verify_agent' object.user.agent.slug %}">Verify</a>
                    {% endif %}
                </td>
        
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif%}
</div>

{% endblock box %}

templates/accounts/document_submit_form.html
{% extends 'dashboard.html' %}

{% load bulma_tags %}

{% block title %}Submit document{% endblock title %}

{% block box %}
    <div class="box">
        <h1 class="title">Submit document(s)</h1>
        <p>Verify your account by submitting the required documents.</p>
        <br>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|bulma }}
            <input type="submit" class="button is-primary is-outlined" value="Submit">
        </form>
        </div>
    </div>
{% endblock box %}

templates/accounts/verify_agent.html
{% extends 'dashboard.html' %}

{% block title %}Verify {{ object.name }}{% endblock title %}

{% block box %}
    <div class="box">
        <h1 class="subtitle">Confirm verification for "{{ object.name }}"</h1>
        <br>
        <a href="{% url 'account:confirm' object.slug %}" class="button is-primary is-outlined">Confirm</a>
    </div>
    <div class="box">
        <div class="columns">
            <div class="column">
                <figure class="image">
                    <img src="{{ object.logo.url }}" alt="">
                </figure>
            </div>
    </div>
{% endblock box %}