accounts/urls.py
'''
All the URL configs here are for the CMS redirects. These paths are only accessable for
authenticated users.
'''

from django.urls import path
from django.views.generic import TemplateView

from .views import AgentSubmitDocumentView, MyDocumentListView, verify_agent, confirm_verification
from blog.views import ArticleCreateView, ArticleDeleteView, ArticleUpdateView, MyArticleListView
from properties.views.house import (HouseCreateView, MyHouseListView, HouseUpdateView,
                                    HouseDeleteView)
from properties.views.apartment import (ApartmentCreateView, ApartmentUpdateView, ApartmentDeleteView, ApartmentUnitCreateView, ApartmentUnitDeleteView, 
                                        ApartmentUnitUpdateView, MyApartmentListView, MyApartmentUnitListView, ApartmentUnitDeleteView)

app_name = 'account'

urlpatterns = [
    path('', TemplateView.as_view(template_name='overview.html'), name='dashboard'),

    # apartments
    path('apartments/', MyApartmentListView.as_view(), name='apartment_list'),
    path('apartments/create/', ApartmentCreateView.as_view(), name='create_apartment'),
    path('apartments/<slug:slug>/update/', ApartmentUpdateView.as_view(), name='update_apartment'),
    path('apartments/<slug:slug>/delete/', ApartmentDeleteView.as_view(), name='delete_apartment'),
    # house 
    path('houses/', MyHouseListView.as_view(), name='house_list'),
    path('houses/add-house/', HouseCreateView.as_view(), name='create_house'),
    path('houses/<slug:slug>/update/', HouseUpdateView.as_view(), name='update_house'),
    path('houses/<slug:slug>/delete/', HouseDeleteView.as_view(), name='delete_house'),
    # apartment units
    path('units/', MyApartmentUnitListView.as_view(), name='apartmentunit_list'),
    path('units/add-unit/', ApartmentUnitCreateView.as_view(), name='create_unit'),
    path('units/<slug:slug>/update/', ApartmentUnitUpdateView.as_view(), name='update_unit'),
    path('units/<slug:slug>/delete/', ApartmentUnitDeleteView.as_view(), name='delete_unit'),
    # document
    path('documents/', MyDocumentListView.as_view(), name='document_list'),
    path('documents/<slug:slug>/verify/', verify_agent, name='verify_agent'),
    path('confirm-verification/<slug:slug>/', confirm_verification, name='confirm'),
    path('submit-document/', AgentSubmitDocumentView.as_view(), name='submit_document'),
    
    # blog articles
    
    path('articles/', MyArticleListView.as_view(), name='article_list'),
    path('articles/write-article/', ArticleCreateView.as_view(), name='write_article'),
    path('articles/<slug:slug>/update/', ArticleUpdateView.as_view(), name='update_article'),
    path('articles/<slug:slug>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

blog/urls.py
from django.urls import path

app_name = 'blog'

from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

properties/urls.py
from django.urls import path

from .views import visitor as visitor_views, apartment

app_name = 'properties'

urlpatterns = [
    path('houses/', visitor_views.HouseListView.as_view(), name='house_list'),
    path('apartments/', visitor_views.ApartmentList.as_view(), name='apartment_list'),
    path('apartment-units/', apartment.ApartmentUnitListView.as_view(), name='unit_list'),
    path('<slug:slug>/', visitor_views.HouseDetailView.as_view(), name='house_detail'),
    path('apartments/<slug:slug>/', visitor_views.ApartmentDetailView.as_view(), name='apartment_detail'),  
    path('apartments/unit/<slug:slug>/', visitor_views.ApartmentUnitDetailView.as_view(), name='unit_detail'),
]

real_estates/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from accounts.views import AgentRegistrationView, AgentProfileCreateView, AgentLisView
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('agents/', AgentLisView.as_view(), name='agent_list'),
    
    # AUTH urls
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', AgentRegistrationView.as_view(), name='register'),
    path('register/success/', AgentProfileCreateView.as_view(), name='registration_success'),
    
    #includes to other apps URLConfigs
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('properties/', include('properties.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse

from djmoney.models.fields import MoneyField


def user_directory_path(instance, file):
    # images will be saved to user seperated folders
    # EXAMPLE: MEDIA_ROOT/properties/owner_1/unit.png
    return 'properties/owner_{}/{}'.format(instance.owner.id, file)


class AbstractPropertyBase(models.Model):
    '''An abastract base model class for both the house and apartment unit model'''
    UNFURNISHED = 'Unfurnished'
    SEMI_FURNISHED = 'Semi furnished'
    FULL_FURNISHED = 'Fully furnished'
    FURNISHING = (
        (UNFURNISHED, 'Unfurnished'),
        (SEMI_FURNISHED,'Semi Furnished'),
        (FULL_FURNISHED, 'Fully Furnished')
    )
    ONE_ROOM = '1 BR'
    TWO_ROOM = '2 BR'
    THREE_ROOM = '3 BR'
    MORE = 'More than 3 BR'
    ROOMS = (
        (ONE_ROOM, '1 Bedroom'),
        (TWO_ROOM, '2 Bedroom'),
        (THREE_ROOM, '3 Bedroom'),
        (MORE, 'More than 3 Bedrooms')
    )

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=55)
    slug = models.SlugField()
    description = models.TextField()
    deposit = MoneyField(max_digits=14, decimal_places=2, default_currency='IDR')
    rent_per_month = MoneyField(max_digits=14, decimal_places=2, default_currency='IDR')
    rent_per_year = MoneyField(max_digits=14, decimal_places=2, default_currency='IDR')

    furnishing = models.CharField(max_length=25, choices=FURNISHING, default=UNFURNISHED)
    bedrooms = models.CharField(max_length=25, choices=ROOMS, default=ONE_ROOM)
    bathroom = models.BooleanField(default=True)
    size = models.PositiveIntegerField(blank=True)
    water_heating = models.BooleanField(default=False)

    available = models.BooleanField(default=True)

    image = models.ImageField(upload_to=user_directory_path, default='properties/default.png')

    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ['-timestamp']

    def __str__(self):
        return self.title 

    def save(self, *args, **kwargs):
        # Override save method to auto calculate total price for
        # property per year
        self.rent_per_year = self.rent_per_month * 12
        super().save(*args, **kwargs)

class House(AbstractPropertyBase):
    ONE = '1'
    TWO = '2'
    THREE = '3'
    MORE = 'More than 3'
    BATHROOMS = (
        (ONE, '1'),
        (TWO, '2'),
        (THREE, '3'),
        (MORE, 'More than 3'),
    )
    garden = models.BooleanField(default=False)
    garage = models.BooleanField(default=False)
    floors = models.PositiveIntegerField()
    bathrooms = models.CharField(max_length=5, choices=BATHROOMS, default=ONE)

    def get_absolute_url(self):
        return reverse('properties:house_detail', kwargs={"slug": self.slug})


class Apartment(models.Model):

    '''Class representing an Apartment'''
    name = models.CharField(max_length=125, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=255)
    # location = .....
    floors = models.IntegerField()
    shopping_mall = models.BooleanField(default=False)
    gym = models.BooleanField(default=False)
    swimming_pool = models.BooleanField(default=False)
    jogging_track = models.BooleanField(default=False)
    laundry = models.BooleanField(default=False)
    security = models.BooleanField(default=False)
    image = models.ImageField(upload_to='properties/apartments', default='properties/default.jpg')
    timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('properties:apartment_detail', kwargs={'slug': self.slug})


class ApartmentUnit(AbstractPropertyBase):
    apartment = models.ForeignKey(Apartment, related_name='units', on_delete=models.CASCADE)
    floor = models.IntegerField(default=3)
    balcony = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('properties:unit_detail', kwargs={'slug': self.slug})
    

    


    
    


    

properties/views/apartment.py
'''
This module contains all the views for the agent.
The views allows the agent to do CRUD operations on the aparmentunit object
'''
from .base import *

from ..models import Apartment, ApartmentUnit, House 


class MyApartmentListView(ListView):
    '''A list view for website visitors'''
    model = Apartment
    template_name = 'properties/my_apartment_list.html'


class ApartmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    '''Create Apartment view for content managers'''
    model = Apartment
    fields = ['name', 'slug', 'description', 'floors', 'shopping_mall',
        'gym', 'swimming_pool', 'jogging_track', 'laundry', 'security', 'image']
    success_message = 'Apartment %(name)s successfully added'


class ApartmentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    '''Update apartment for content managers'''
    model = Apartment
    fields = ['name', 'slug', 'description', 'floors', 'shopping_mall',
        'gym', 'swimming_pool', 'jogging_track', 'laundry', 'security', 'image']
    success_message = '%(name)s has been successfully updated'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApartmentDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Apartment
    success_url = reverse_lazy('account:apartment_list')
    success_message = 'Apartment has been deleted'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ApartmentDeleteView, self).delete(request, *args, **kwargs)


class ApartmentUnitListView(ListView):
    model = ApartmentUnit


class MyApartmentUnitListView(LoginRequiredMixin, ListView):
    model = ApartmentUnit
    template_name = 'properties/my_apartment_unit.html'

    def get_queryset(self):
        return ApartmentUnit.objects.filter(owner=self.request.user)


class ApartmentUnitCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = ApartmentUnit
    fields = ['apartment', 'title', 'slug', 'deposit', 'rent_per_month', 'description',
        'furnishing', 'bedrooms', 'size', 'water_heating', 'available', 
        'floor', 'balcony','image']
    success_message = 'Unit "%(title)s" successfully added'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApartmentUnitUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ApartmentUnit
    fields = ['apartment', 'title', 'slug', 'deposit', 'rent_per_month', 'description',
        'furnishing', 'bedrooms', 'size', 'water_heating', 'available', 
        'floor', 'balcony','image', 'available']
    success_message = '%(title)s successfully updated'
    template_name = 'properties/apartmentunit_update.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ApartmentUnitDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = ApartmentUnit
    success_url = reverse_lazy('account:apartmentunit_list')
    success_message = '%(title)s has been deleted'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(ApartmentUnitDeleteView, self).delete(request, *args, **kwargs)


    

properties/views/base.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView

properties/views/house.py
'''
This module contains the views for the agent.
eg. Creating, Retreiving, Updating and deleting their objects.
'''
from .base import *
from ..models import House


class MyHouseListView(LoginRequiredMixin, ListView):
    '''Personal list of object for the authenticated agent'''
    model = House
    template_name = 'properties/agent_house_list.html'

    def get_queryset(self):
        # only show agent owned property
        return House.objects.filter(owner=self.request.user)


# view should only be accessable for property agents
class HouseCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = House
    fields = ['title', 'slug', 'deposit', 'rent_per_month', 'description',
        'furnishing', 'bedrooms', 'bathrooms', 'floors', 'size', 'water_heating', 'image']
    template_name = 'properties/house_create_form.html'
    success_message = '%(title)s successfully added'

    def form_valid(self, form):
        # assign owner field to logged in user
        form.instance.owner = self.request.user
        return super().form_valid(form)


class HouseUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = House
    fields = ['title', 'slug', 'deposit', 'rent_per_month', 'description',
        'furnishing', 'bedrooms', 'bathrooms', 'floors', 'size', 'water_heating', 'available', 'image']
    template_name = 'properties/house_update_form.html'
    success_message = '%(title)s has been updated successfully'

    def form_valid(self, form):
        # assign owner field to logged in user
        form.instance.owner = self.request.user
        return super().form_valid(form)


class HouseDeleteView(LoginRequiredMixin, DeleteView):
    model = House
    success_url = reverse_lazy('account:house_list')
    success_message = 'Successfully deleted'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(HouseDeleteView, self).delete(request, *args, **kwargs)

properties/views/visitor.py
'''
The views here are for the website visitors that are looking for properties.
'''
from .base import *

from ..models import Apartment, ApartmentUnit, House


class ApartmentList(ListView):
    model = Apartment


class ApartmentDetailView(DetailView):
    model = Apartment


class ApartmentUnitDetailView(DetailView):
    model = ApartmentUnit


class HouseListView(ListView):
    # List view for houses that are available
    queryset = House.objects.filter(available=True)


class HouseDetailView(DetailView):
    model = House

templates/properties/apartment_confirm_delete.html
{% extends 'dashboard.html' %}

{% block title %}Delete {{ object.title }}{% endblock title %}

{% block box %}
    <div class="box">
        <div class="columns">
            <div class="column">
                <figure class="image">
                    <img src="{{ object.image.url }}" alt="">
                </figure>
            </div>
            <div class="column">
                <form action="" method="post">
                    {% csrf_token %}
                    <h1 class="subtitle">Confirm you want to delete "{{object.title }}"</h1>
                    <input type="submit" class="button is-success is-outlined" value="Confirm">
                </form>
            </div>
        </div>
    </div>
{% endblock box %}

templates/properties/apartment_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.name }}{% endblock title %}

{% block content %}
    <div class="box">
        <h1 class="title has-text-centered">{{ object.name }}</h1>
        <figure class="image is-16by9">
            <img src="{{ object.image.url }}" alt="">
        </figure>
    </div>
    <div class="box">
        <div class="columns">
            <div class="column is-6">
                <h1 class="title">Apartment Facilitites</h1>
                <strong>Floors</strong><br>
                <p>{{ object.floors }}</p> 
                
                <strong>Shopping Mall</strong><br>
                {% if object.shopping_mall %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}
                
                <strong>Gym</strong><br>
                {% if object.gym %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}
                
                <strong>Swimming Pool</strong><br>
                {% if object.swimming_pool %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}                
                
                <strong>Jogging Track</strong><br>
                {% if object.jogging_track %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}                
                
                <strong>Laundry</strong><br>
                {% if object.laundry %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}                
                
                <strong>Security</strong>
                {% if object.security %}
                    <p>Yes</p>
                {% else %}
                    <p>No</p>
                {% endif %}

                <strong>Available units</strong><br>
                {{ object.units.count }}
            </div>
            <div class="column is-6">
                <h1 class="title">Description</h1>
                {{object.description|linebreaks}}
            </div>
        </div>
    </div>

    <h1 class="title has-text-centered">{{ object.name }} Units</h1>

    <!-- UNITS -->
    <div class="columns">
        {% for unit in object.units.all %}
        <div class="column is-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">{{ unit.title}}</div>
                </div>
                <div class="card-image">
                    <a href="{{ unit.get_absolute_url }}">
                        <figure class="image is-5by3">
                            <img src="{{ unit.image.url }}" alt="{{ unit.title }}">
                        </figure>
                    </a>
                </div>
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="{{ unit.owner.agent.logo.url }}" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-5">{{ unit.owner.agent.name }}</p>
                            <p class="subtitle is-6">added on {{ unit.timestamp|date:'d M Y'}}</p>
                        </div>
                    </div>
                    <div class="content">

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% if not object.units.all %}
    <div class="notification">
        No units for this apartment yet
    </div>
    {% endif %}
{% endblock content %}

templates/properties/apartment_form.html
{% extends 'dashboard.html' %}

{% load bulma_tags %}

{% block title %}{% endblock title %}

{% block box %}
    <div class="box">
        <h1 class="title">Add new apartment</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|bulma }}
            <input type="submit" value="Submit" class="button is-primary is-outlined">
        </form>
    </div>
{% endblock box %}

templates/properties/apartment_list.html
{% extends 'base.html' %}

{% block title %}Apartments{% endblock title %}

{% block content %}
    <div class="box">
        <h1 class="title">Apartments in Nairobi</h1>
        <p></p>
    </div>

    <!-- INFO when DB is not filled with aparment object yet -->
    {% if not apartment_list %}
    <div class="notification">
        No apartments yet.
    </div>
    {% endif %}

    <div class="columns is-multiline">
        <!-- Loop through apartment objects -->
        {% for object in apartment_list %}
        <div class="column is-3">
            <div class="card">
                <div class="card-image">
                    <figure class="image">
                        <a href="{{ object.get_absolute_url }}">
                            <img src="{{ object.image.url }}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <h1 class="subtitle">{{ object.name }}</h1>
                </div>
            </div>
        </div>   
        {% endfor %}
    </div>
{% endblock content %}

templates/properties/apartmentunit_confirm_delete.html
{% extends 'dashboard.html' %}

{% block title %}Delete {{ object.title }}{% endblock title %}

{% block box %}
    <div class="box">
        <div class="columns">
            <div class="column">
                <figure class="image">
                    <img src="{{ object.image.url }}" alt="">
                </figure>
            </div>
            <div class="column">
                <form action="" method="post">
                    {% csrf_token %}
                    <h1 class="subtitle">Confirm you want to delete "{{object.title }}"</h1>
                    <input type="submit" class="button is-success is-outlined" value="Confirm">
                </form>
            </div>
        </div>
    </div>
{% endblock box %}

templates/properties/apartmentunit_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
    <div class="box">
        <div class="columns">
            <div class="column is-8">
                <figure class="image">
                    <a href="{{ object.image.url }}">
                        <img src="{{ object.image.url }}" alt="{{ object.title }}">
                    </a>
                </figure>
            </div>
            <div class="column">
                <div class="field is-grouped is-grouped-multiline">
                    <div class="control">
                        <div class="tags has-addons">
                            <span class="tag is-dark is-small">Apartment</span>
                            <span class="tag is-info is-small"><a href="{{ object.apartment.get_absolute_url }}" class="has-text-white">{{ object.apartment }}</a></span>
                        </div>
                    </div>
                </div>
                <h1 class="title">{{ object.title }}</h1>
                <small>
                    <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                    <span>{{ object.timestamp|date:'d M Y' }}</span> 
                    
                </small>
                <br><br>
                <h2 class="subtitle">Description</h2>
                {{ object.description|safe|linebreaks }}
            </div>
        </div>
    </div>

    <div class="columns">
        <div class="column is-8">
            <div class="box">
                <h1 class="title is-4">Cost details</h1>
                <br>
                <h1 class="subtitle is-6">Deposit</h1>
                <p>{{ object.deposit }}</p>
                
                <h1 class="subtitle is-6">Rent per month</h1>
                <p>{{ object.rent_per_month }}</p>

                <h1 class="subtitle is-6">Total per year</h1>
                <p>{{ object.rent_per_year }}</p>
            </div>

            <br>
            
            <!--  PROPERTY DETAILS -->
            <div class="box">
                <h1 class="title is-4">Property Details</h1>
                <div class="columns">
                    <div class="column">
                        <h1 class="subtitle is-6">Furnishing</h1>
                        <p>{{ object.furnishing }}</p>
                        
                        <h1 class="subtitle is-6">Bedrooms</h1>
                        <p>{{ object.bedrooms }}</p>

                        <h1 class="subtitle is-6">Bathrooms</h1>
                        <p>{{ object.bathrooms }}</p>

                        <h1 class="subtitle is-6">Size</h1>
                        <p>{{ object.size }}</p>
                    </div>

                    <div class="column">
                        <h1 class="subtitle is-6">Water heating</h1>
                        {% if object.waterheating %}
                            <p>Available</p>
                        {% else %}
                            <p>Not available</p>
                        {% endif %}

                        <h1 class="subtitle is-6">Garage</h1>
                        {% if object.garage %}
                            <p>Yes</p>
                        {% else %}
                            <p>No</p>
                        {% endif %}

                        <h1 class="subtitle is-6">Garden</h1>
                        {% if object.garden %}
                            <p>Yes</p>
                        {% else %}
                            <p>No</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        
        <!-- AGENT DETAIL -->

        <div class="column">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">
                        <a href="#" class="has-text-black">{{ object.owner.agent.name }}</a>
                    </div>
                </div>
                <div class="card-image">
                    <figure class="image">
                        <a href="{{ object.owner.agent.logo.url }}">
                            <img src="{{ object.owner.agent.logo.url }}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content">
                        <h1 class="subtitle is-6">Contact</h1>
                        <p><strong>Phonenumber</strong>: <a href="tel:+" class="has-text-grey">{{ object.owner.agent.phonenumber }}</a></p>
                        <p><strong>Email</strong>: <a href="mailto:" class="has-text-grey">{{ object.owner.email }}</a></p>
                        <hr>
                        {% if not object.owner.agent.verified %}
                            <small>Agent has not been verified yet</small>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/properties/my_apartment_list.html
{% extends 'dashboard.html' %}

{% block title %}{% endblock title %}

{% block box %}
    {% for object in apartment_list %}
    <div class="box">
        <article class="media">
            <div class="media-left">
                <figure class="image is-128x128">
                    <a href="{{ object.get_absolute_url }}">
                        <img src="{{ object.image.url }}" alt="">
                    </a>
                </figure>
            </div>
            <div class="media-content">
                <div class="content">
                    <p>
                        <small><strong>added {{ object.timestamp|timesince }} ago</strong></small>
                        <br>
                        <a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
                    </p>
                </div>
                <nav class="level is-mobile">
                    <div class="level-left">
                        <!-- UPDate -->
                        <a href="{% url 'account:update_apartment' object.slug %}" class="level-item">
                            <span class="icon"><i class="fas fa-edit"></i></span>
                        </a>
                        <!-- Delete -->
                        <a href="{% url 'account:delete_apartment' object.slug %}" class="level-item">
                            <span class="icon"><i class="fas fa-trash-alt"></i></span>
                        </a>
                    </div>
                </nav>
            </div>
        </article>
    </div>
    {% endfor %}
{% endblock box %}

templates/properties/my_apartment_unit.html
{% extends 'dashboard.html' %}

{% block title %}{{ request.user.agent.name }}{% endblock title %}

{% block box %}
    {% if not apartmentunit_list %}
    <div class="notification">
        <p><strong>No units yet.</p>
    </div>
    {% endif %}
    
    
    <div class="columns">
        {% for object in apartmentunit_list %}
        <div class="column">
            <div class="box">
                <article class="media">
                    <div class="media-left">
                        <figure class="image is-128x128">
                            <a href="{{ object.get_absolute_url }}">
                                <img src="{{ object.image.url }}" alt="">
                            </a>
                        </figure>
                    </div>
                    <div class="media-content">
                        <div class="content">
                            <p>
                                <small><strong>added {{ object.timestamp|timesince }} ago - {{object.timestamp }}</strong></small>
                                <br>
                                <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                            </p>
                        </div>
                        <!-- OBJECT ACTIONS -->
                        <nav class="level is-mobile">
                            <div class="level-left">
                                <a href="{% url 'account:update_unit' object.slug %}" class="level-item"> <!--EDIT-->
                                    <span class="icon is-small">
                                        <i class="fas fa-edit"></i>
                                    </span>
                                </a>
                                <a href="{% url 'account:delete_unit' object.slug %}" class="level-item">
                                    <span class="icon is-small">
                                        <i class="fas fa-trash-alt"></i>
                                    </span>
                                </a>
                            </div>
                        </nav>
                        <!-- END OBJECT ACTIONS -->
                    </div>
                </article>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock box %}