accounts/urls.py
'''
All the URL configs here are for the CMS redirects. These paths are only accessable for
authenticated users.
'''

from django.urls import path
from django.views.generic import TemplateView

from .views import AgentSubmitDocumentView, MyDocumentListView, verify_agent, confirm_verification
from blog.views import ArticleCreateView, ArticleDeleteView, ArticleUpdateView, MyArticleListView
from properties.views.house import (HouseCreateView, MyHouseListView, HouseUpdateView,
                                    HouseDeleteView)
from properties.views.apartment import (ApartmentCreateView, ApartmentUpdateView, ApartmentDeleteView, ApartmentUnitCreateView, ApartmentUnitDeleteView, 
                                        ApartmentUnitUpdateView, MyApartmentListView, MyApartmentUnitListView, ApartmentUnitDeleteView)

app_name = 'account'

urlpatterns = [
    path('', TemplateView.as_view(template_name='overview.html'), name='dashboard'),

    # apartments
    path('apartments/', MyApartmentListView.as_view(), name='apartment_list'),
    path('apartments/create/', ApartmentCreateView.as_view(), name='create_apartment'),
    path('apartments/<slug:slug>/update/', ApartmentUpdateView.as_view(), name='update_apartment'),
    path('apartments/<slug:slug>/delete/', ApartmentDeleteView.as_view(), name='delete_apartment'),
    # house 
    path('houses/', MyHouseListView.as_view(), name='house_list'),
    path('houses/add-house/', HouseCreateView.as_view(), name='create_house'),
    path('houses/<slug:slug>/update/', HouseUpdateView.as_view(), name='update_house'),
    path('houses/<slug:slug>/delete/', HouseDeleteView.as_view(), name='delete_house'),
    # apartment units
    path('units/', MyApartmentUnitListView.as_view(), name='apartmentunit_list'),
    path('units/add-unit/', ApartmentUnitCreateView.as_view(), name='create_unit'),
    path('units/<slug:slug>/update/', ApartmentUnitUpdateView.as_view(), name='update_unit'),
    path('units/<slug:slug>/delete/', ApartmentUnitDeleteView.as_view(), name='delete_unit'),
    # document
    path('documents/', MyDocumentListView.as_view(), name='document_list'),
    path('documents/<slug:slug>/verify/', verify_agent, name='verify_agent'),
    path('confirm-verification/<slug:slug>/', confirm_verification, name='confirm'),
    path('submit-document/', AgentSubmitDocumentView.as_view(), name='submit_document'),
    
    # blog articles
    
    path('articles/', MyArticleListView.as_view(), name='article_list'),
    path('articles/write-article/', ArticleCreateView.as_view(), name='write_article'),
    path('articles/<slug:slug>/update/', ArticleUpdateView.as_view(), name='update_article'),
    path('articles/<slug:slug>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

blog/urls.py
from django.urls import path

app_name = 'blog'

from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

real_estates/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from accounts.views import AgentRegistrationView, AgentProfileCreateView, AgentLisView
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('agents/', AgentLisView.as_view(), name='agent_list'),
    
    # AUTH urls
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', AgentRegistrationView.as_view(), name='register'),
    path('register/success/', AgentProfileCreateView.as_view(), name='registration_success'),
    
    #includes to other apps URLConfigs
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('properties/', include('properties.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

def user_directory_path(instance, file):
    return 'blog/user_{}/{}'.format(instance, file)


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=122)
    slug = models.SlugField()
    subtitle = models.CharField(max_length=122, blank=True)
    body = models.TextField()
    image = models.ImageField(upload_to=user_directory_path)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', kwargs={'slug': self.slug,})
    

blog/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .models import Article


class ArticleListView(ListView):
    # Retrieve list of article objects
    model = Article


class ArticleDetailView(DetailView):
    # retrieve single article object
    model = Article


class MyArticleListView(LoginRequiredMixin, ListView):
    # Retrieve list of article objects owned by user
    model = Article
    template_name = 'blog/my_articles_list.html'

    def get_queryset(self):
        # filter this list for the logged in user
        return Article.objects.filter(user=self.request.user)


class ArticleCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    # create article object
    model = Article
    fields = ['title', 'subtitle', 'slug', 'body', 'image']
    success_message = '%(title)s successfully posted'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    # update existing article object
    model = Article
    fields = ['title', 'subtitle', 'image']
    success_message = '%(title)s has been updated'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ArticleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    # delete article object
    model = Article
    success_message = 'Article has been deleted!'
    success_url = reverse_lazy('account:article_list')
    

templates/blog/article_confirm_delete.html
{% extends 'dashboard.html' %}

{% block title %}Delete {{ object.title }}{% endblock title %}

{% block box %}
<div class="box">
    <form action="" method="post">
        {% csrf_token %}
        <h1 class="subtitle">Confirm you want to delete "{{object.title }}"</h1>
        <input type="submit" class="button is-success is-outlined" value="Confirm">
    </form>
</div>
{% endblock box %}

templates/blog/article_detail.html
{% extends 'base.html' %}

{% block title %}{{ object.title }}{% endblock title %}

{% block content %}
<div class="columns">
    <div class="column is-three-fifths is-offset-one-fifth">
        <div class="box">
            <figure class="image">
                <img src="{{ object.image.url }}" alt="">
            </figure>
        </div>
    </div>
</div>

<div class="columns">
    <div class="column is-three-fifths is-offset-one-fifth">
        <div class="box">
            <h1 class="title">{{ object.title|title }}</h1>
            <h2 class="subtitle">{{ object.subtitle }}</h2>
            <small>
                <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                <span>{{ object.timestamp|date:'d M Y' }}</span>
            </small>
            <br><br>
            {{ object.body|linebreaks|safe }}
        </div>
        <!-- AUTHOR BOX -->
        <div class="box">
            <p class="subtitle">About the author</p>
            <article class="media">
                <div class="media-left">
                    <figure class="image is-64x64">
                        <img src="{{ object.user.contentmanager.avatar }}" alt="">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                        <strong>{{ object.user.contentmanager }}</strong>
                        <br>
                        {{ object.user.contentmanager.bio }}
                        </p>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>
{% endblock content %}

templates/blog/article_form.html
{% extends 'dashboard.html' %}

{% load bulma_tags %}

{% block title %}Write new post{% endblock title %}

{% block box %}
    
    {% if not object %}
        <div class="notification">
            This will be your first post! Happy writing!
        </div>
    {% endif %}
    
    <div class="box">
        <h1 class="title">
            <span class="icon"><i class="fas fa-pen-nib"></i></span>
            <span>Write</span>
        </h1>
        <br>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|bulma }}
            <input type="submit" value="Post" class="button is-primary is-outlined">
        </form>
    </div>
{% endblock box %}

templates/blog/article_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
    <div class="box">
        <h1 class="title">Our blog</h1>
        <p>Read about Jakarta</p>
    </div>
    {% if not article_list %}
    <p class="has-text-centered">No blog post yet.</p>
    {% endif %}

    <hr>

    <div class="columns is-multiline">
        {% for object in article_list %}
        <div class="column is-3">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">{{ object.title }}</div>
                </div>
                <div class="card-image">
                    <figure class="image is-16by9">
                        <a href="{{ object.get_absolute_url }}">
                            <img src="{{ object.image.url }}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="{{ object.user.contentmanager.avatar }}" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p>
                                <strong>{{ object.user.contentmanager }}</strong>
                                <br>
                                <small>added on {{ object.timestamp|date:'d M Y'}}</small>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/blog/my_articles_list.html
<!-- LIST OF ARTICLES FOR THE CONTENT MANAGER -->
{% extends 'dashboard.html' %}

{% block title %}My articles{% endblock title %}

{% block box %}
    {% for object in article_list %}
        <div class="box">
            <div class="media">
                <div class="media-left">
                    <figure class="image is-128x128">
                        <img src="{{ object.image.url }}" alt="">
                    </figure>
                </div>
                <div class="media-content">
                    <div class="content">
                        <p>
                            <small><strong>posted {{ object.timestamp|timesince }}</strong></small>
                            <br>
                            <a href="{{ object.get_absolute_url }}">{{ object.title }}</a>
                        </p>
                    </div>
                    <nav class="level is-mobile">
                        <div class="level-left">
                            <!-- UPDate -->
                            <a href="{% url 'account:update_article' object.slug %}" class="level-item">
                                <span class="icon"><i class="fas fa-edit"></i></span>
                            </a>
                            <a href="{% url 'account:delete_article' object.slug %}" class="level-item">
                                <span class="icon"><i class="fas fa-trash-alt"></i></span>
                            </a>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}