accounts/urls.py
'''
All the URL configs here are for the CMS redirects. These paths are only accessable for
authenticated users.
'''

from django.urls import path
from django.views.generic import TemplateView

from .views import AgentSubmitDocumentView, MyDocumentListView, verify_agent, confirm_verification
from blog.views import ArticleCreateView, ArticleDeleteView, ArticleUpdateView, MyArticleListView
from properties.views.house import (HouseCreateView, MyHouseListView, HouseUpdateView,
                                    HouseDeleteView)
from properties.views.apartment import (ApartmentCreateView, ApartmentUpdateView, ApartmentDeleteView, ApartmentUnitCreateView, ApartmentUnitDeleteView, 
                                        ApartmentUnitUpdateView, MyApartmentListView, MyApartmentUnitListView, ApartmentUnitDeleteView)

app_name = 'account'

urlpatterns = [
    path('', TemplateView.as_view(template_name='overview.html'), name='dashboard'),

    # apartments
    path('apartments/', MyApartmentListView.as_view(), name='apartment_list'),
    path('apartments/create/', ApartmentCreateView.as_view(), name='create_apartment'),
    path('apartments/<slug:slug>/update/', ApartmentUpdateView.as_view(), name='update_apartment'),
    path('apartments/<slug:slug>/delete/', ApartmentDeleteView.as_view(), name='delete_apartment'),
    # house 
    path('houses/', MyHouseListView.as_view(), name='house_list'),
    path('houses/add-house/', HouseCreateView.as_view(), name='create_house'),
    path('houses/<slug:slug>/update/', HouseUpdateView.as_view(), name='update_house'),
    path('houses/<slug:slug>/delete/', HouseDeleteView.as_view(), name='delete_house'),
    # apartment units
    path('units/', MyApartmentUnitListView.as_view(), name='apartmentunit_list'),
    path('units/add-unit/', ApartmentUnitCreateView.as_view(), name='create_unit'),
    path('units/<slug:slug>/update/', ApartmentUnitUpdateView.as_view(), name='update_unit'),
    path('units/<slug:slug>/delete/', ApartmentUnitDeleteView.as_view(), name='delete_unit'),
    # document
    path('documents/', MyDocumentListView.as_view(), name='document_list'),
    path('documents/<slug:slug>/verify/', verify_agent, name='verify_agent'),
    path('confirm-verification/<slug:slug>/', confirm_verification, name='confirm'),
    path('submit-document/', AgentSubmitDocumentView.as_view(), name='submit_document'),
    
    # blog articles
    
    path('articles/', MyArticleListView.as_view(), name='article_list'),
    path('articles/write-article/', ArticleCreateView.as_view(), name='write_article'),
    path('articles/<slug:slug>/update/', ArticleUpdateView.as_view(), name='update_article'),
    path('articles/<slug:slug>/delete/', ArticleDeleteView.as_view(), name='delete_article'),
]

blog/urls.py
from django.urls import path

app_name = 'blog'

from . import views

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article_list'),
    path('<slug:slug>/', views.ArticleDetailView.as_view(), name='article_detail'),
]

properties/urls.py
from django.urls import path

from .views import visitor as visitor_views, apartment

app_name = 'properties'

urlpatterns = [
    path('houses/', visitor_views.HouseListView.as_view(), name='house_list'),
    path('apartments/', visitor_views.ApartmentList.as_view(), name='apartment_list'),
    path('apartment-units/', apartment.ApartmentUnitListView.as_view(), name='unit_list'),
    path('<slug:slug>/', visitor_views.HouseDetailView.as_view(), name='house_detail'),
    path('apartments/<slug:slug>/', visitor_views.ApartmentDetailView.as_view(), name='apartment_detail'),  
    path('apartments/unit/<slug:slug>/', visitor_views.ApartmentUnitDetailView.as_view(), name='unit_detail'),
]

real_estates/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path
from django.views.generic import TemplateView

from accounts.views import AgentRegistrationView, AgentProfileCreateView, AgentLisView
from pages.views import home

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('about/', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    path('agents/', AgentLisView.as_view(), name='agent_list'),
    
    # AUTH urls
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', AgentRegistrationView.as_view(), name='register'),
    path('register/success/', AgentProfileCreateView.as_view(), name='registration_success'),
    
    #includes to other apps URLConfigs
    path('account/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('properties/', include('properties.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

properties/views/base.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bulma CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/sandstone/bulmaswatch.min.css">

    <!-- Fontawesome CDN -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.8/css/mdb.min.css" rel="stylesheet">

    <title>{% block title %}{% endblock title %}</title>
</head>

<body style="font-family: 'Source Sans Pro', sans-serif;">


    <nav class="navbar navbar-expand-lg navbar-dark cyan darken-3">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#"> Real Estate
            </a>
            {% if not request.user.is_authenticated %}

            <ul class="navbar-nav mr-auto mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}">Login<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            </ul>

            {% else %}

            <a class="nav-item nav-link" href="{% url 'account:dashboard' %}"> <span class="icon"><i
                        class="fas fa-tachometer-alt"></i></span>
                <span>Dashboard</span>
            </a>

            {% endif %}

        </div>
    </nav>
    <!-- Navbar -->

    <section class="section">
        <div class="container">

            <!-- MESSAGES -->
            {% include 'snippets/messages.html' %}

            <!-- Small tag message -->
            {% if request.user.is_authenticated %}
            <div class="field is-grouped is-grouped-multiline">
                <div class="control">
                    <div class="tags has-addons">
                        <span class="tag is-dark is-medium icon"><i class="far fa-user-circle"></i></span>
                        <span class="tag is-info is-medium"><a href="{% url 'account:dashboard' %}"
                                class="has-text-white">{{ request.user }}</a></span>
                    </div>
                </div>
            </div>
            {% endif %}

            <!-- Navigation tabs -->
            <div class="tabs">
                <ul>
                    <li><a href="{% url 'home' %}"> Home</a></li>
                    <li><a href="{% url 'properties:house_list' %}">Houses</a></li>
                    <li><a href="{% url 'properties:apartment_list' %}">Apartments</a></li>
                    <li><a href="{% url 'properties:unit_list' %}">Units</a></li>
                    <li><a href="{% url 'blog:article_list' %}">Blog</a></li>
                    <li><a href="{% url 'about' %}">About</a></li>
                </ul>
            </div>

            <!-- Main Content  -->
            {% block content %}{% endblock content %}

        </div>
    </section>

    <footer class="page-footer font-small cyan darken-3">

        <!-- Footer Elements -->
        <div class="container">

            <!-- Grid row-->
            <div class="row">

                <!-- Grid column -->
                <div class="col-md-8 py-5">
                    <div class="mb-5 flex-center">

                        <!-- Facebook -->
                        <a class="fb-ic">
                            <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <!-- Twitter -->
                        <a class="tw-ic">
                            <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <!-- Google +-->
                        <a class="gplus-ic">
                            <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <!--Linkedin -->
                        <a class="li-ic">
                            <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <!--Instagram-->
                        <a class="ins-ic">
                            <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
                        </a>
                        <!--Pinterest-->
                        <a class="pin-ic">
                            <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
                        </a>
                    </div>
                </div>
                <div class="col-md-4 py-5">
                    <p><a href="{% url 'login' %}">Login</a></p>
                    <p><a href="{% url 'register' %}">Register</a></p>
                    <p><a href="{% url 'agent_list' %}">Our agents</a></p>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row-->

        </div>
        <!-- Footer Elements -->

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2018 Copyright:
            <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
        </div>
        <!-- Copyright -->

    </footer>
    <!-- Footer -->
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js">
    </script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.8/js/mdb.min.js">
    </script>
</body>

</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bulma CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/sandstone/bulmaswatch.min.css">

    <!-- Fontawesome CDN -->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=VT323|Share+Tech+Mono" rel="stylesheet">
    
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="font-family: 'Share Tech Mono', monospace;">
    <!-- NAV -->
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'account:dashboard' %}" style="font-family: 'VT323', monospace; font-size: 34px">  
                    Dashboard
                </a>
            </div>
            <div class="navbar-menu">
                <div class="navbar-start">
                    {% if request.user.is_agent %}
                    <a href="" class="navbar-item">Property Agent</a>
                    <a href="{% url 'account:house_list' %}" class="navbar-item">My Houses</a>
                    <a href="{% url 'account:apartmentunit_list' %}" class="navbar-item">My Apartment Units</a>
                    {% else %}
                    <a href="" class="navbar-item">Content Manager</a>
                    <a href="{% url 'account:apartment_list' %}" class="navbar-item">Apartments</a>
                    <a href="{% url 'account:article_list' %}" class="navbar-item">Articles</a>
                    {% endif %}
                </div>
                
                <div class="navbar-end">
                    <a href="{% url 'home' %}" class="navbar-item">
                        <span class="icon"><i class="fas fa-home"></i></span>
                        <span>Website</span>
                    </a>
                    <a href="{% url 'logout' %}" class="navbar-item">
                        <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                        <span>Logout</span>
                    </a>
                </div>
            </div>
        </div>
    </nav>

    <!-- MAIN section -->
    <section class="section">
        <div class="container">
            <!-- VERIFICATION REMINDER FOR AGENT -->
            {% if not request.user.agent.verified and request.user.is_agent %}
            <div class="notification is-danger has-text-white">
                Your account has not been verified yet. Please verify by oploading a document <a href="{% url 'account:submit_document' %}">here</a>
            </div>
            {% endif %}

            <!-- Welcoming message -->
            <div class="notification">
                {% if request.user.is_agent %}
                    <span class="icon"><i class="far fa-user-circle"></i></span>
                    <span>Welcome {{ request.user.agent.name }}</span>
                {% else %}
                    <span class="icon"><i class="far fa-user-circle"></i></span>
                    <span>Welcome {{ request.user.contentmanager }}</span>
                {% endif %}
            </div>

            <!-- DISPLAY success messages -->
            {% include 'snippets/messages.html' %}
        
            <div class="columns">
                <!-- Side panel -->
                <div class="column is-3">
                    <!-- User Name -->
                    <div class="card">
                        <div class="card-image">
                            <figure class="image">
                                {% if request.user.is_agent %}
                                    <img src="{{ request.user.agent.logo.url }}" alt="">
                                {% else %}
                                    <img src="{{ request.user.contentmanager.avatar }}" alt="">
                                {% endif %}
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="content">
                                {% if request.user.is_agent %}
                                    <h1 class="subtitle is-5">{{ request.user.agent.name }}</h1>
                                    <small>
                                        {% if request.user.agent.verified %}
                                        <hr>
                                        Verified
                                        {% endif %}
                                    </small>
                                {% else %}
                                    <h1 class="title is-5">{{ request.user.contentmanager }}</h1>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <br>

                    <nav class="panel">
                        <p class="panel-heading">Quick Actions</p>
                        
                        {% if request.user.is_agent %}
                        <!-- TABS for agents -->
                        <div class="panel-block">
                            <a href="{% url 'account:create_house' %}">
                                <span class="icon"><i class="fas fa-plus"></i></span>
                                <span>Add House</span>
                            </a>
                        </div>
                        <div class="panel-block">
                            <a href="{% url 'account:create_unit' %}">
                                <span class="icon"><i class="fas fa-plus"></i></span>
                                <span>Add Apartment Unit</span>
                            </a>
                        </div>
                        
                        {% else %}
                        <!-- TABS for staff -->
                        <div class="panel-block">
                            <a href="{% url 'account:create_apartment' %}">
                                <span class="icon"><i class="fas fa-plus"></i></span>
                                <span>Add Apartment</span>
                            </a>
                        </div>
                        <div class="panel-block">
                            <a href="{% url 'account:write_article' %}">
                                <span class="icon"><i class="fas fa-pen-nib"></i></span>
                                <span>Write Post</span> 
                            </a>
                        </div>
                        <div class="panel-block">
                            <a href="{% url 'account:document_list' %}">
                            <span class="icon"><i class="fas fa-paperclip"></i></span>
                            <span>Documents & Verifications</span> 
                            </a>
                        </div>

                        {% endif %}
                        
                        <div class="panel-block">
                            <a href="{% url 'logout' %}">
                                <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                                <span>Logout</span>
                            </a>
                        </div>
                    </nav>
                </div>
                <!-- Dashboard overview -->
                <div class="column">
                    {% if request.user.is_agent %}
                    
                    {% else %}
                    <div class="box">
                        <nav class="level">
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Articles</p>
                                    <p class="title">{{ articles_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Apartments</p>
                                    <p class="title">{{ apartment_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Apartment Units</p>
                                    <p class="title">{{ apartmentunit_count }}</p>  
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Houses</p>
                                    <p class="title">{{ house_count }}</p>
                                </div>
                            </div>
                        </nav>
                    </div>
                    {% endif %}

                    {% block box %}
                    {% endblock box %}   
                </div>
            </div>
        </div>
    </section>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% load article_tags %}
{% load properties_tags %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="columns is-multiline">
        
        <div class="column is-6">
            <div class="card">
                <div class="card-image">
                    <figure class="image">
                        <a href="{% url 'properties:house_list' %}">
                            <img src="{% static 'img/house.jpg' %}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content has-text-centered">
                        <p>Search for <a href="{% url 'properties:house_list' %}">houses</a> to rent</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="column is-6">
            <div class="card">
                <div class="card-image">
                    <figure class="image">
                        <a href="{% url 'properties:apartment_list' %}">
                            <img src="{% static 'img/unit.jpg' %}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="content has-text-centered">
                        <p>Search for <a href="{% url 'properties:apartment_list' %}">Apartment units</a> to rent</p>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="column is-12 has-text-centered">
            <hr>
            <h1 class="title">Latest blog posts</h1>
            <p>See<a href="{% url 'blog:article_list' %}"> all</a></p>
        </div>

        {% latest_articles as article_list %}
        <!-- Iterate through articles via custom template tag -->
        {% for object in article_list %}
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">{{ object.title }}</div>
                </div>
                <div class="card-image">
                    <figure class="image is-16by9">
                        <a href="{{ object.get_absolute_url }}">
                            <img src="{{ object.image.url }}" alt="">
                        </a>
                    </figure>
                </div>
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="{{ object.user.contentmanager.avatar }}" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <strong>by {{ object.user.contentmanager }}</strong><br>
                                    <span class="icon"><i class="fas fa-calendar-alt"></i></span>
                                    <span>{{ object.timestamp|date:'d M Y' }}</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    
        {% apartmentunit_list as unit_list %}
        {% if unit_list %}
        <div class="column is-12 has-text-centered">
                <h1 class="title">Newest Apartment Units</h1>
            </div>
        </div>

        <!-- Iterate through latest apartment units via custom template tag -->
        
        {% for unit in unit_list %}
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">{{ unit.title}}</div>
                </div>
                <div class="card-image">
                    <a href="{{ unit.get_absolute_url }}">
                        <figure class="image is-5by3">
                            <img src="{{ unit.image.url }}" alt="{{ unit.title }}">
                        </figure>
                    </a>
                </div>
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="{{ unit.owner.agent.logo.url }}" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-5">{{ unit.owner.agent.name }}</p>
                            <p class="subtitle is-6">added on {{ unit.timestamp|date:'d M Y'}}</p>
                        </div>
                    </div>
                    <div class="content">

                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        <div class="column is-12 has-text-centered">
            <h1 class="title">Newest houses</h1>
        </div>
    
        {% house_list as house_list %}
        {% for house in house_list %}
        <div class="column is-4">
            <div class="card">
                <div class="card-header">
                    <div class="card-header-title">{{ house.title}}</div>
                </div>
                <div class="card-image">
                    <a href="{{ house.get_absolute_url }}">
                        <figure class="image is-5by3">
                            <img src="{{ house.image.url }}" alt="{{ house.title }}">
                        </figure>
                    </a>
                </div>
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="{{ house.owner.agent.logo.url }}" alt="">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-5">{{ house.owner.agent.name }}</p>
                            <p class="subtitle is-6">added on {{ house.timestamp|date:'d M Y'}}</p>
                        </div>
                    </div>
                    <div class="content">
    
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock content %}

templates/overview.html
{% extends 'dashboard.html' %}

{% block title %}{% endblock title %}

{% block box %}
    <div class="box">
        {% if request.user.is_agent %}
        <h1 class="title">Managing your properties</h1>
        <div class="columns">
            <div class="column is-4">
                <p>Your personal CMS to manage all your properties. </p>
            </div>
        </div>
        {% endif %}
    </div>
{% endblock box %}